## 1. 라이브러리 참조

In [1]:
# import sys
# sys.path.append("D:\\")

from IPython.display import display, Markdown
from pandas import DataFrame, crosstab
#from helpers import *

## 2. 파일 불러오기 & 자료형 확인

In [2]:
import pandas as pd

df = pd.read_excel(r"C:\Users\user\Documents\데이터분석\workspace\팀프로젝트다시\output\모델링용_데이터셋_최종.xlsx")
print(df.info())
display(df.head())

<class 'pandas.DataFrame'>
RangeIndex: 7230 entries, 0 to 7229
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   리뷰_번호   7230 non-null   str
 1   국가      7230 non-null   str
 2   제품_순위   7230 non-null   int64
 3   별점      7230 non-null   int64
 4   Y       7230 non-null   int64
 5   보습      7230 non-null   int64
 6   향       7230 non-null   int64
 7   발림성     7230 non-null   int64
 8   자극      7230 non-null   int64
 9   용기      7230 non-null   int64
 10  배송      7230 non-null   int64
 11  기능      7230 non-null   int64
 12  가격      7230 non-null   int64
dtypes: int64(11), str(2)
memory usage: 859.9 KB
None

         리뷰_번호   국가  제품_순위  별점  Y  보습  향  발림성  자극  용기  배송  기능  가격
0  RU_P01_0001  러시아      1   5  1   0  0    1   0   1   0   1   0
1  RU_P01_0002  러시아      1   5  1   1  0    0   0   0   0   0   0
2  RU_P01_0003  러시아      1   5  1   1  1    0   0   1   0   1   0
3  RU_P01_0004  러시아      1   5  1   0  0    0   0   0   0   0   0
4  RU_P01_0005  러시아      1   5  1   0  1    1   0   1   1   0   0

## 3. 데이터 중복 점검

In [3]:
df0 = my_qtcheck.check_duplicates(df, drop=True)

중복된 행의 수: 0

## 4. 결측치 점검

In [4]:
my_qtcheck.check_missing_values(df0)

       Missing Count  Missing Ratio (%)
리뷰_번호              0                0.0
국가                 0                0.0
제품_순위              0                0.0
별점                 0                0.0
Y                  0                0.0
보습                 0                0.0
향                  0                0.0
발림성                0                0.0
자극                 0                0.0
용기                 0                0.0
배송                 0                0.0
재구매                0                0.0
기능                 0                0.0
가격                 0                0.0

## 5. 속성값이 모두 0인 행 개수 확인

In [3]:
cols = [
    '보습', '향', '발림성', '자극', '용기',
    '배송', '기능', '가격'
]

# 9개 속성이 모두 0인 행 찾기
zero_rows = (df[cols] == 0).all(axis=1)

# 전체 개수 확인
print("속성값이 모두 0인 행 개수:", zero_rows.sum())

# 국가별 개수 확인
print("\n국가별 속성값 전체 0인 행 개수:")
display(df.loc[zero_rows, '국가'].value_counts())

# 해당 행 직접 확인
display(df[zero_rows])


# 한국만
kr_zero = df.loc[zero_rows]
kr_zero = kr_zero[kr_zero['국가'] == '한국']

with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(kr_zero)

속성값이 모두 0인 행 개수: 546

국가별 속성값 전체 0인 행 개수:

국가
러시아    280
한국      99
미국      90
일본      77
Name: count, dtype: int64

            리뷰_번호   국가  제품_순위  별점  Y  보습  향  발림성  자극  용기  배송  기능  가격
3     RU_P01_0004  러시아      1   5  1   0  0    0   0   0   0   0   0
8     RU_P01_0009  러시아      1   5  1   0  0    0   0   0   0   0   0
22    RU_P01_0023  러시아      1   5  1   0  0    0   0   0   0   0   0
32    RU_P01_0033  러시아      1   5  1   0  0    0   0   0   0   0   0
38    RU_P01_0039  러시아      1   5  1   0  0    0   0   0   0   0   0
...           ...  ...    ...  .. ..  .. ..  ...  ..  ..  ..  ..  ..
7102  KR_P10_0073   한국     10   5  1   0  0    0   0   0   0   0   0
7111  KR_P10_0082   한국     10   5  1   0  0    0   0   0   0   0   0
7120  KR_P10_0091   한국     10   5  1   0  0    0   0   0   0   0   0
7124  KR_P10_0095   한국     10   5  1   0  0    0   0   0   0   0   0
7129  KR_P10_0100   한국     10   5  1   0  0    0   0   0   0   0   0

[546 rows x 13 columns]

            리뷰_번호  국가  제품_순위  별점  Y  보습  향  발림성  자극  용기  배송  기능  가격
5312  KR_P01_0022  한국      1   5  1   0  0    0   0   0   0   0   0
5318  KR_P01_0028  한국      1   5  1   0  0    0   0   0   0   0   0
5366  KR_P01_0076  한국      1   5  1   0  0    0   0   0   0   0   0
5410  KR_P01_0120  한국      1   1  0   0  0    0   0   0   0   0   0
5445  KR_P01_0155  한국      1   1  0   0  0    0   0   0   0   0   0
5470  KR_P01_0180  한국      1   1  0   0  0    0   0   0   0   0   0
5508  KR_P02_0018  한국      2   5  1   0  0    0   0   0   0   0   0
5509  KR_P02_0019  한국      2   5  1   0  0    0   0   0   0   0   0
5514  KR_P02_0024  한국      2   5  1   0  0    0   0   0   0   0   0
5516  KR_P02_0026  한국      2   5  1   0  0    0   0   0   0   0   0
5517  KR_P02_0027  한국      2   5  1   0  0    0   0   0   0   0   0
5521  KR_P02_0031  한국      2   5  1   0  0    0   0   0   0   0   0
5536  KR_P02_0046  한국      2   5  1   0  0    0   0   0   0   0   0
5552  KR_P02_0062  한국      2   5  1   0  0    0   0   0   0   0   0
5554  KR_P02_0064  한국      2   5  1   0  0    0   0   0   0   0   0
5693  KR_P03_0003  한국      3   5  1   0  0    0   0   0   0   0   0
5701  KR_P03_0011  한국      3   5  1   0  0    0   0   0   0   0   0
5730  KR_P03_0040  한국      3   5  1   0  0    0   0   0   0   0   0
5733  KR_P03_0043  한국      3   5  1   0  0    0   0   0   0   0   0
5750  KR_P03_0060  한국      3   5  1   0  0    0   0   0   0   0   0
5752  KR_P03_0062  한국      3   5  1   0  0    0   0   0   0   0   0
5768  KR_P03_0078  한국      3   5  1   0  0    0   0   0   0   0   0
5791  KR_P03_0101  한국      3   1  0   0  0    0   0   0   0   0   0
5894  KR_P04_0004  한국      4   5  1   0  0    0   0   0   0   0   0
5907  KR_P04_0017  한국      4   5  1   0  0    0   0   0   0   0   0
5920  KR_P04_0030  한국      4   5  1   0  0    0   0   0   0   0   0
5929  KR_P04_0039  한국      4   5  1   0  0    0   0   0   0   0   0
5953  KR_P04_0063  한국      4   5  1   0  0    0   0   0   0   0   0
5955  KR_P04_0065  한국      4   5  1   0  0    0   0   0   0   0   0
5971  KR_P04_0081  한국      4   5  1   0  0    0   0   0   0   0   0
5982  KR_P04_0092  한국      4   5  1   0  0    0   0   0   0   0   0
5983  KR_P04_0093  한국      4   5  1   0  0    0   0   0   0   0   0
5997  KR_P04_0107  한국      4   1  0   0  0    0   0   0   0   0   0
6026  KR_P04_0136  한국      4   1  0   0  0    0   0   0   0   0   0
6060  KR_P04_0170  한국      4   1  0   0  0    0   0   0   0   0   0
6082  KR_P04_0192  한국      4   1  0   0  0    0   0   0   0   0   0
6114  KR_P05_0024  한국      5   5  1   0  0    0   0   0   0   0   0
6117  KR_P05_0027  한국      5   5  1   0  0    0   0   0   0   0   0
6185  KR_P05_0095  한국      5   5  1   0  0    0   0   0   0   0   0
6188  KR_P05_0098  한국      5   5  1   0  0    0   0   0   0   0   0
6189  KR_P05_0099  한국      5   5  1   0  0    0   0   0   0   0   0
6229  KR_P05_0139  한국      5   1  0   0  0    0   0   0   0   0   0
6291  KR_P06_0001  한국      6   5  1   0  0    0   0   0   0   0   0
6300  KR_P06_0010  한국      6   5  1   0  0    0   0   0   0   0   0
6319  KR_P06_0029  한국      6   5  1   0  0    0   0   0   0   0   0
6322  KR_P06_0032  한국      6   5  1   0  0    0   0   0   0   0   0
6330  KR_P06_0040  한국      6   5  1   0  0    0   0   0   0   0   0
6347  KR_P06_0057  한국      6   5  1   0  0    0   0   0   0   0   0
6349  KR_P06_0059  한국      6   5  1   0  0    0   0   0   0   0   0
6361  KR_P06_0071  한국      6   5  1   0  0    0   0   0   0   0   0
6380  KR_P06_0090  한국      6   5  1   0  0    0   0   0   0   0   0
6440  KR_P06_0150  한국      6   2  0   0  0    0   0   0   0   0   0
6470  KR_P07_0005  한국      7   5  1   0  0    0   0   0   0   0   0
6486  KR_P07_0021  한국      7   5  1   0  0    0   0   0   0   0   0
6487  KR_P07_0022  한국      7   5  1   0  0    0   0   0   0   0   0
6497  KR_P07_0032  한국      7   5  1   0  0    0   0   0   0   0   0
6506  KR_P07_0041  한국      7   5  1   0  0    0   0   0   0   0   0
6508  KR_P07_0043  한국      7   5  1   0  0    0   0   0   0   0   0
6512  KR_P07_0047  한국      7   5  1   0  0    0   0   0   0   0   0
6513  KR_P07_0048  한국      7   5  1   0  0    0   0   0   0   0   0
6523  KR_P07_0058  한국      7   5  1   0  0    0   0   0   0   0   0
6546  KR_P07_0081  한국      7   5  1   0  0    0   0   0   0   0   0
6569  KR_P07_0104  한국      7   1  0   0  0    0   0   0   0   0   0
6583  KR_P07_0118  한국      7   1  0   0  0    0   0   0   0   0   0
6589  KR_P07_0124  한국      7   1  0   0  0    0   0   0   0   0   0
6591  KR_P07_0126  한국      7   1  0   0  0    0   0   0   0   0   0
6650  KR_P08_0015  한국      8   5  1   0  0    0   0   0   0   0   0
6687  KR_P08_0052  한국      8   5  1   0  0    0   0   0   0   0   0
6706  KR_P08_0071  한국      8   5  1   0  0    0   0   0   0   0   0
6708  KR_P08_0073  한국      8   5  1   0  0    0   0   0   0   0   0
6713  KR_P08_0078  한국      8   5  1   0  0    0   0   0   0   0   0
6718  KR_P08_0083  한국      8   5  1   0  0    0   0   0   0   0   0
6746  KR_P08_0111  한국      8   1  0   0  0    0   0   0   0   0   0
6804  KR_P08_0169  한국      8   2  0   0  0    0   0   0   0   0   0
6809  KR_P08_0174  한국      8   2  0   0  0    0   0   0   0   0   0
6845  KR_P09_0016  한국      9   5  1   0  0    0   0   0   0   0   0
6849  KR_P09_0020  한국      9   5  1   0  0    0   0   0   0   0   0
6856  KR_P09_0027  한국      9   5  1   0  0    0   0   0   0   0   0
6860  KR_P09_0031  한국      9   5  1   0  0    0   0   0   0   0   0
6866  KR_P09_0037  한국      9   5  1   0  0    0   0   0   0   0   0
6877  KR_P09_0048  한국      9   5  1   0  0    0   0   0   0   0   0
6906  KR_P09_0077  한국      9   5  1   0  0    0   0   0   0   0   0
6907  KR_P09_0078  한국      9   5  1   0  0    0   0   0   0   0   0
6911  KR_P09_0082  한국      9   5  1   0  0    0   0   0   0   0   0
6953  KR_P09_0124  한국      9   1  0   0  0    0   0   0   0   0   0
6967  KR_P09_0138  한국      9   1  0   0  0    0   0   0   0   0   0
6995  KR_P09_0166  한국      9   2  0   0  0    0   0   0   0   0   0
7031  KR_P10_0002  한국     10   5  1   0  0    0   0   0   0   0   0
7039  KR_P10_0010  한국     10   5  1   0  0    0   0   0   0   0   0
7042  KR_P10_0013  한국     10   5  1   0  0    0   0   0   0   0   0
7057  KR_P10_0028  한국     10   5  1   0  0    0   0   0   0   0   0
7072  KR_P10_0043  한국     10   5  1   0  0    0   0   0   0   0   0
7078  KR_P10_0049  한국     10   5  1   0  0    0   0   0   0   0   0
7096  KR_P10_0067  한국     10   5  1   0  0    0   0   0   0   0   0
7102  KR_P10_0073  한국     10   5  1   0  0    0   0   0   0   0   0
7111  KR_P10_0082  한국     10   5  1   0  0    0   0   0   0   0   0
7120  KR_P10_0091  한국     10   5  1   0  0    0   0   0   0   0   0
7124  KR_P10_0095  한국     10   5  1   0  0    0   0   0   0   0   0
7129  KR_P10_0100  한국     10   5  1   0  0    0   0   0   0   0   0

## 6. 속성값이 모두 0인 행 제거

In [5]:
df1 = df.loc[~zero_rows].copy()

print("삭제 전 행 개수:", len(df))
print("삭제 후 행 개수:", len(df1))
print("삭제된 행 개수:", len(df) - len(df1))

display(df1.head())

삭제 전 행 개수: 7230
삭제 후 행 개수: 6684
삭제된 행 개수: 546

         리뷰_번호   국가  제품_순위  별점  Y  보습  향  발림성  자극  용기  배송  기능  가격
0  RU_P01_0001  러시아      1   5  1   0  0    1   0   1   0   1   0
1  RU_P01_0002  러시아      1   5  1   1  0    0   0   0   0   0   0
2  RU_P01_0003  러시아      1   5  1   1  1    0   0   1   0   1   0
4  RU_P01_0005  러시아      1   5  1   0  1    1   0   1   1   0   0
5  RU_P01_0006  러시아      1   5  1   1  0    0   0   0   0   0   0